{% set name = "esi-syncopy" %}
{% set version = "2023.07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/esi_syncopy-2023.7.tar.gz
  sha256: c4336e6d74e8b952cec752075450361069e9a2211a4ff888295e985e47bbef85

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.12
    - poetry
    - ruamel.yaml >=0.16,<0.17
    - wheel
    - setuptools
  run:
    - python >=3.8, <3.11
    - h5py >=3.7, <4
    - dask[distributed]
    - dask-jobqueue >=0.8
    - matplotlib-base >=3.5
    - fooof
    - numpy <2.0, >=1.10
    - pip
    - scipy >=1.10
    - tqdm >=4.31
    - psutil
    - natsort
    - toml
    - ipdb

test:
  imports:
    - syncopy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://syncopy.org
  summary: Systems Neuroscience Computing in Python
  description: |
    Syncopy is a Python toolkit for user-friendly, large-scale electrophysiology data analysis.
    It is scalable to accommodate very large datasets. It automatically makes use of available
    computing resources and is developed with built-in parallelism in mind. Syncopy is compatible with
    the Matlab toolbox FieldTrip.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://syncopy.readthedocs.io
  dev_url: https://github.com/esi-neuroscience/syncopy

extra:
  recipe-maintainers:
    - tensionhead
    - pantaray
    - dfsp-spirit
